[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "pref_voting"
version = "0.1.22"
description = "pref_voting is a Python packaging that contains tools to reason about election profiles and margin graphs, and implementations of a variety of preferential voting methods."
authors = ["Eric Pacuit <epacuit@umd.edu>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/voting-tools/pref_voting"
repository = "https://github.com/voting-tools/pref_voting"

[tool.poetry.dependencies]
python = "^3.6"
numba = "^0.56.0"
numpy = "^1.22.0"
networkx = "^2.8.5"
tabulate = "^0.8.10"
random2 = "^1.0.1"
matplotlib = "^3.5.2"

[tool.poetry.dev-dependencies]
